# Generated by Django 3.0.6 on 2020-05-29 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.CharField(max_length=254, unique=True)),
                ('first_name', models.CharField(default='', max_length=254)),
                ('middle_name', models.CharField(blank=True, default='', max_length=254)),
                ('last_name', models.CharField(default='', max_length=254)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
