# Generated by Django 3.0.6 on 2020-05-29 19:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FullThrottle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59))),
                ('logout_time', models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59))),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='FullThrottle.User')),
            ],
        ),
    ]
