# Generated by Django 3.0.6 on 2020-05-31 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FullThrottle', '0002_activityperiod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.AddField(
            model_name='user',
            name='timezone',
            field=models.CharField(default='', max_length=10),
        ),
    ]
